name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build-and-install:
    permissions:
      contents: read
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          submodules: recursive

      - name: Build kernels and tests for the CPU backend
        run: make all ALPAKA_ACCELERATOR_FLAG=ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED -j10

      - name: Run tests
        run: make test -j10
